apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: demo
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: demo
  resources:
    requests:
      storage: 100Mi
